### ISSUE TITLE
Informations in developer-instructions.md need to be updated

### ISSUE THREAD

**Issue by ywf3m** [computationalmystic/augur-group16#6]
- The link in the "new features" need to be updated.
- The link of "updated file list" need to be updated after new document added.

**Comment by springfitnesstechnology** [comment]
What do you mean by updated? Is the current link old?

**Comment by calebheinzman** [comment]
What do you mean by updated? Is the current link old?

**Comment by ywf3m** [comment]
When the developer-instructions.md, some related documentations and some informations are not updated to the latest version but links to them are added, so the link need to be updated, but now it is done.
